### PR TITLE
feat: Add Feedback-widget

### PR DESCRIPTION
**Pull request by elwinschmitz**
See a preview: https://grateful-swallow.static.domains/general/support-contact/

### CODE REVIEW

**Comment by tijsziere** [comment]
@elwinschmitz  Checks have failed

**Comment by elwinschmitz** [comment]
I didn't even touch those files. 😢

**Comment by elwinschmitz** [comment]
Ow yeah. I updated the Markdownlint-tool...

Makes sense...

**Review by tijsziere — APPROVED** [review]

**Comment by elwinschmitz** [comment]
@tijsziere There was still some "example content" in this, that wasn't supposed to be merged in yet... 🤦 

For example, the question "how many feedback-options do we want?"
And the "link to feedback-form" is just a placeholder now...

**Comment by tijsziere** [comment]
Haha, okay
Don't think that is a problem though

**Pull request merged**
